### ISSUE TITLE
Issue Report on Lack of Support for Chinese in Addon

### ISSUE THREAD

**Issue by i-cooltea** [AmanRathoreP/Anki-Addon-for-Multiple-Decks-Creation#2]
I would like to report an issue regarding a certain addon. 
First of all, I want to praise this addon for being very practical and saving me a lot of time, significantly improving my work efficiency.  

However, I have found that this addon does not support Chinese. As a user who frequently uses Chinese, it is quite inconvenient for me. The addon only supports English, which is very troublesome for me. Every time I need to use Chinese to complete a task, I have to first create it in English and then convert it to Chinese, which is time-consuming.

I hope that this addon can support Chinese, so that I and other Chinese users can use it more conveniently. I believe that this improvement will make the addon more popular and attract more users.

Thank you for your attention to this issue, and I look forward to seeing improvements in this addon. If you need any further information, please feel free to contact me.

Thank you.  

My file content is as follows

```
Anki_2025单词卡牌::bkc::Unit 1
Anki_2025单词卡牌::bkc::Unit 2
Anki_2025单词卡牌::bkc::Unit 3
Anki_2025单词卡牌::bkc::Unit 4
Anki_2025单词卡牌::bkc::Unit 5
Anki_2025单词卡牌::bkc::Unit 6
Anki_2025单词卡牌::bkc::Unit 7
Anki_2025单词卡牌::bkc::Unit 8
```

**Comment by AmanRathoreP** [comment]
Well, I'm not exactly sure what you are talking about as addon allows you to import decks with names written in any language that your machine supports.

https://github.com/AmanRathoreP/Anki-Addon-for-Multiple-Decks-Creation/assets/93982282/51355f68-832c-4347-9282-116441f4c27c

**Comment by i-cooltea** [comment]
I'm not sure if it's caused by Chinese characters, 
but I can create it successfully by trying to change Chinese into English.

The following is anki's debugging information.
```    
    Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
    Platform: macOS-10.15.7-x86_64-i386-64bit
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2024-01-08 21:24:26
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2023-07-02T03:55, 'None', mod]
    Anki Tooltips ['1840818335', 2023-02-20T14:35, 'None', '']
    AnkiWebView Inspector ['31746032', 2023-06-28T03:26, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2023-07-25T07:48, 'None', '']
    CrowdAnki JSON exportimport Edit history Collaborate on deck creation ['1788670778', 2023-10-31T02:57, 'None', '']
    Dancing Baloney Allows changing wallpapers with live preview ['378638814', 2020-03-27T13:28, 'None', mod]
    Export Cards As Text ['1112021968', 2021-07-08T15:57, 'None', '']
    Export in CSV format ['1478130872', 2019-01-22T02:21, 'None', '']
    FastWordQuery-Qt6 ['103636257', 2023-09-09T13:15, 'None', '']
    Image Editor ['307397307', 2022-09-08T12:09, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
    Life Drain ['715575551', 2023-06-20T19:41, 'None', '']
    Multiple decks creator ['461193445', 2023-09-12T23:06, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T19:24, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    103636257 1046608507 1112021968 1374772155 1436550454 1478130872 1771074083 1788670778 1840818335 307397307 31746032 378638814 461193445 715575551 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['ankisyncd', 0, 'None', '']
    Anki IPA ['799647424', 2022-10-24T00:26, 'None', mod]
    Anki Simulator ['817108664', 2021-08-08T03:24, 'None', '']
    AnkiConnect ['2055492159', 2023-04-12T01:20, 'None', '']
    Automatic Dark Night Mode ['446355629', 2021-05-16T02:22, 'None', '']
    Change subdecks configuration ['751420631', 2018-11-26T21:26, 'None', '']
    Fast Word Query 2 ['1501719123', 2022-08-31T18:55, 'None', '']
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T11:10, 'None', '']
    HTML Window source ['1214415810', 2020-02-18T21:20, 'None', '']
    Large and Colorful Buttons ['1829090218', 2018-10-03T01:41, 'None', '']
    Mini Format Pack ['295889520', 2018-07-25T01:45, 'None', '']
    Word Query ['775418273', 2018-01-01T01:07, 'None', '']
    Wordsworth Word Frequency Ranker ['696663192', 2019-09-02T09:54, 'None', '']
```

**Comment by i-cooltea** [comment]
Perhaps it is the reason for the difference in operating environment.

**Comment by i-cooltea** [comment]
Does this plugin provide error logs

**Comment by i-cooltea** [comment]
When I opened Anki through the console, this problem miraculously disappeared.
The following is the content output from the console.
Hoping to provide you with useful information.

```
461193445/src/my_user_interactive_GUI.py:36:'Qt.AlignCenter' will stop working. Please use 'Qt.AlignmentFlag.AlignCenter' instead.
461193445/src/my_user_interactive_GUI.py:41:'QAbstractItemView.MultiSelection' will stop working. Please use 'QAbstractItemView.SelectionMode.MultiSelection' instead.
addons21/461193445/main.py:11:'MyCustomDialog.exec_()' is deprecated. Please use 'MyCustomDialog.exec()'
```


The console opening method is as follows

refer to https://addon-docs.ankiweb.net/console-output.html#showing-the-console

```
[Showing the Console](https://addon-docs.ankiweb.net/console-output.html#showing-the-console)
[Windows](https://addon-docs.ankiweb.net/console-output.html#windows)
If you start Anki via the anki-console.bat file in C:\Users\user\AppData\Local\Programs\Anki (or C:\Program Files\Anki), a separate console window will appear.

[macOS](https://addon-docs.ankiweb.net/console-output.html#macos)
Open Terminal.app, then enter the following text and hit enter:

/Applications/Anki.app/Contents/MacOS/anki
[Linux](https://addon-docs.ankiweb.net/console-output.html#linux)
Open a terminal/xterm, then run Anki with anki
```

**Comment by AmanRathoreP** [comment]
Well first of all sorry for replying so late.
The addon works properly only with QT5 not with QT6 and you are using QT6 that's why you are facing these errors.

![image](https://github.com/AmanRathoreP/Anki-Addon-for-Multiple-Decks-Creation/assets/93982282/586154df-dfdd-434b-b6c2-f2869683b038)

**Comment by i-cooltea** [comment]
Can it be upgraded to support QT6? I would be happy to submit a merge request for this plugin.

**Comment by AmanRathoreP** [comment]
Yes one can upgrade the addon to make it compatible with QT6.
You can submit pull request and after checking it's compatibility with QT6 as well as with QT5, I'll merge it to master branch,
